services:
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - db
    networks:
      - app_network
    restart: unless-stopped
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
